package com.ganjx.cinema.entity;

// Generated 2015-10-14 10:59:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import com.vion.core.domain.entity.IEntity;

/**
 * CinemaWithLowPrecision generated by hbm2java
 */
@Entity
@Table(name = "cinema_with_low_precision")
public class CinemaWithLowPrecision implements IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer cinemaCode;
	private String cinemaName;
	private Integer status;

	public CinemaWithLowPrecision() {
	}

	public CinemaWithLowPrecision(Integer cinemaCode, String cinemaName,
			Integer status) {
		this.cinemaCode = cinemaCode;
		this.cinemaName = cinemaName;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cinema_code")
	public Integer getCinemaCode() {
		return this.cinemaCode;
	}

	public void setCinemaCode(Integer cinemaCode) {
		this.cinemaCode = cinemaCode;
	}

	@Column(name = "cinema_name")
	public String getCinemaName() {
		return this.cinemaName;
	}

	public void setCinemaName(String cinemaName) {
		this.cinemaName = cinemaName;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
