package com.ganjx.cinema.entity;

// Generated 2015-10-14 17:17:08 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.vion.core.domain.entity.IEntity;

/**
 * DivisonCode generated by hbm2java
 */
@Entity
@Table(name = "divison_code")
public class DivisonCode implements IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private Integer pid;
	private List<DivisonCode> children = new ArrayList<>();

	public DivisonCode() {
	}

	public DivisonCode(int id) {
		this.id = id;
	}

	public DivisonCode(int id, String name, Integer pid) {
		this.id = id;
		this.name = name;
		this.pid = pid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pid")
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Transient
	public List<DivisonCode> getChildren() {
		return children;
	}

	public void setChildren(List<DivisonCode> children) {
		this.children = children;
	}
	
	@Override
	public String toString() {
		return "DivisonCode [id=" + id + ", name=" + name + ", pid=" + pid
				+ "]";
	}

	
}
