package com.ganjx.cinema.entity;

// Generated 2015-10-14 10:59:00 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import com.vion.core.domain.entity.IEntity;

/**
 * CinemaRaw generated by hbm2java
 */
@Entity
@Table(name = "cinema_raw")
public class CinemaRaw implements IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer cinemaCode;
	private String cinemaName;
	private BigDecimal cinemaLng;
	private BigDecimal cinemaLat;

	public CinemaRaw() {
	}

	public CinemaRaw(Integer cinemaCode, String cinemaName,
			BigDecimal cinemaLng, BigDecimal cinemaLat) {
		this.cinemaCode = cinemaCode;
		this.cinemaName = cinemaName;
		this.cinemaLng = cinemaLng;
		this.cinemaLat = cinemaLat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cinema_code")
	public Integer getCinemaCode() {
		return this.cinemaCode;
	}

	public void setCinemaCode(Integer cinemaCode) {
		this.cinemaCode = cinemaCode;
	}

	@Column(name = "cinema_name")
	public String getCinemaName() {
		return this.cinemaName;
	}

	public void setCinemaName(String cinemaName) {
		this.cinemaName = cinemaName;
	}

	@Column(name = "cinema_lng", precision = 9, scale = 6)
	public BigDecimal getCinemaLng() {
		return this.cinemaLng;
	}

	public void setCinemaLng(BigDecimal cinemaLng) {
		this.cinemaLng = cinemaLng;
	}

	@Column(name = "cinema_lat", precision = 9, scale = 6)
	public BigDecimal getCinemaLat() {
		return this.cinemaLat;
	}

	public void setCinemaLat(BigDecimal cinemaLat) {
		this.cinemaLat = cinemaLat;
	}

}
