package com.ganjx.cinema.entity;

// Generated 2015-10-14 10:59:00 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import com.vion.core.domain.entity.IEntity;

/**
 * Attribution generated by hbm2java
 */
@Entity
@Table(name = "attribution")
public class Attribution implements IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer cinemaCode;
	private String classificationName;
	private String name;
	private String address;
	private Integer distance;
	private String type;
	private String tag;
	private String price;
	private String shopHours;
	private String overallRating;
	private String tasteRating;
	private String serviceRating;
	private String environmentRating;
	private String facilityRating;
	private String hygieneRating;
	private String technologyRating;
	private String imageNum;
	private String grouponNum;
	private String discountNum;
	private String commentNum;
	private String favoriteNum;
	private String checkinNum;

	public Attribution() {
	}

	public Attribution(Integer cinemaCode, String classificationName,
			String name, String address, Integer distance, String type,
			String tag, String price, String shopHours, String overallRating,
			String tasteRating, String serviceRating, String environmentRating,
			String facilityRating, String hygieneRating,
			String technologyRating, String imageNum, String grouponNum,
			String discountNum, String commentNum, String favoriteNum,
			String checkinNum) {
		this.cinemaCode = cinemaCode;
		this.classificationName = classificationName;
		this.name = name;
		this.address = address;
		this.distance = distance;
		this.type = type;
		this.tag = tag;
		this.price = price;
		this.shopHours = shopHours;
		this.overallRating = overallRating;
		this.tasteRating = tasteRating;
		this.serviceRating = serviceRating;
		this.environmentRating = environmentRating;
		this.facilityRating = facilityRating;
		this.hygieneRating = hygieneRating;
		this.technologyRating = technologyRating;
		this.imageNum = imageNum;
		this.grouponNum = grouponNum;
		this.discountNum = discountNum;
		this.commentNum = commentNum;
		this.favoriteNum = favoriteNum;
		this.checkinNum = checkinNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cinema_code")
	public Integer getCinemaCode() {
		return this.cinemaCode;
	}

	public void setCinemaCode(Integer cinemaCode) {
		this.cinemaCode = cinemaCode;
	}

	@Column(name = "classification_name", length = 15)
	public String getClassificationName() {
		return this.classificationName;
	}

	public void setClassificationName(String classificationName) {
		this.classificationName = classificationName;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "distance")
	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	@Column(name = "type", length = 60)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "tag", length = 60)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "price", length = 20)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "shop_hours", length = 20)
	public String getShopHours() {
		return this.shopHours;
	}

	public void setShopHours(String shopHours) {
		this.shopHours = shopHours;
	}

	@Column(name = "overall_rating", length = 5)
	public String getOverallRating() {
		return this.overallRating;
	}

	public void setOverallRating(String overallRating) {
		this.overallRating = overallRating;
	}

	@Column(name = "taste_rating", length = 5)
	public String getTasteRating() {
		return this.tasteRating;
	}

	public void setTasteRating(String tasteRating) {
		this.tasteRating = tasteRating;
	}

	@Column(name = "service_rating", length = 5)
	public String getServiceRating() {
		return this.serviceRating;
	}

	public void setServiceRating(String serviceRating) {
		this.serviceRating = serviceRating;
	}

	@Column(name = "environment_rating", length = 5)
	public String getEnvironmentRating() {
		return this.environmentRating;
	}

	public void setEnvironmentRating(String environmentRating) {
		this.environmentRating = environmentRating;
	}

	@Column(name = "facility_rating", length = 3)
	public String getFacilityRating() {
		return this.facilityRating;
	}

	public void setFacilityRating(String facilityRating) {
		this.facilityRating = facilityRating;
	}

	@Column(name = "hygiene_rating", length = 3)
	public String getHygieneRating() {
		return this.hygieneRating;
	}

	public void setHygieneRating(String hygieneRating) {
		this.hygieneRating = hygieneRating;
	}

	@Column(name = "technology_rating", length = 3)
	public String getTechnologyRating() {
		return this.technologyRating;
	}

	public void setTechnologyRating(String technologyRating) {
		this.technologyRating = technologyRating;
	}

	@Column(name = "image_num", length = 10)
	public String getImageNum() {
		return this.imageNum;
	}

	public void setImageNum(String imageNum) {
		this.imageNum = imageNum;
	}

	@Column(name = "groupon_num", length = 10)
	public String getGrouponNum() {
		return this.grouponNum;
	}

	public void setGrouponNum(String grouponNum) {
		this.grouponNum = grouponNum;
	}

	@Column(name = "discount_num", length = 10)
	public String getDiscountNum() {
		return this.discountNum;
	}

	public void setDiscountNum(String discountNum) {
		this.discountNum = discountNum;
	}

	@Column(name = "comment_num", length = 10)
	public String getCommentNum() {
		return this.commentNum;
	}

	public void setCommentNum(String commentNum) {
		this.commentNum = commentNum;
	}

	@Column(name = "favorite_num", length = 10)
	public String getFavoriteNum() {
		return this.favoriteNum;
	}

	public void setFavoriteNum(String favoriteNum) {
		this.favoriteNum = favoriteNum;
	}

	@Column(name = "checkin_num", length = 10)
	public String getCheckinNum() {
		return this.checkinNum;
	}

	public void setCheckinNum(String checkinNum) {
		this.checkinNum = checkinNum;
	}

}
