package com.ganjx.cinema.entity;

// Generated 2015-10-16 12:43:15 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import com.vion.core.domain.entity.IEntity;

/**
 * TCinemaAddress generated by hbm2java
 */
@Entity
@Table(name = "t_cinema_address")
public class TCinemaAddress implements IEntity{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String city;
	private String county;
	private String cinemaName;
	private String address;
	private String tel;
	private String theatreChain;
	private BigDecimal baiduLng;
	private BigDecimal baiduLat;
	private BigDecimal goolgeLng;
	private BigDecimal googleLat;
	private String source;
	
	private Integer cityId;
	private Integer countyId;

	public TCinemaAddress() {
	}

	public TCinemaAddress(String city, String county, String cinemaName,
			String address, String tel, String theatreChain) {
		this.city = city;
		this.county = county;
		this.cinemaName = cinemaName;
		this.address = address;
		this.tel = tel;
		this.theatreChain = theatreChain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "city", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "county", length = 20)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "cinema_name", length = 30)
	public String getCinemaName() {
		return this.cinemaName;
	}

	public void setCinemaName(String cinemaName) {
		this.cinemaName = cinemaName;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "tel", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "theatre_chain", length = 64)
	public String getTheatreChain() {
		return this.theatreChain;
	}

	public void setTheatreChain(String theatreChain) {
		this.theatreChain = theatreChain;
	}

	@Column(name = "google_lng", precision = 9, scale = 6)
	public BigDecimal getGoolgeLng() {
		return goolgeLng;
	}

	public void setGoolgeLng(BigDecimal goolgeLng) {
		this.goolgeLng = goolgeLng;
	}

	@Column(name = "google_lat", precision = 9, scale = 6)
	public BigDecimal getGoogleLat() {
		return googleLat;
	}

	public void setGoogleLat(BigDecimal googleLat) {
		this.googleLat = googleLat;
	}

	@Override
	public String toString() {
		return "TCinemaAddress [id=" + id + ", city=" + city + ", county="
				+ county + ", cinemaName=" + cinemaName + ", address="
				+ address + ", tel=" + tel + ", theatreChain=" + theatreChain
				+ ", baiduLng=" + baiduLng + ", baiduLat=" + baiduLat
				+ ", goolgeLng=" + goolgeLng + ", googleLat=" + googleLat
				+ ", source=" + source + "]";
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "baidu_lng", precision = 20, scale = 6)
	public BigDecimal getBaiduLng() {
		return baiduLng;
	}

	public void setBaiduLng(BigDecimal baiduLng) {
		this.baiduLng = baiduLng;
	}

	@Column(name = "baidu_lat", precision = 20, scale = 6)
	public BigDecimal getBaiduLat() {
		return baiduLat;
	}

	public void setBaiduLat(BigDecimal baiduLat) {
		this.baiduLat = baiduLat;
	}

	@Column(name = "city_id")
	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Column(name = "county_id")
	public Integer getCountyId() {
		return countyId;
	}

	public void setCountyId(Integer countyId) {
		this.countyId = countyId;
	}
	
	

}
